[build]
  base    = "hoft-app"
  command = "npm run build"
  publish = "hoft-app/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
